<template>
	<div>
		<v-toolbar>
			<v-toolbar-title>Learn</v-toolbar-title>
			<v-spacer></v-spacer>
			<v-btn icon>
				<v-icon>search</v-icon>
			</v-btn>
		</v-toolbar>
		<iframe id="ytplayer" type="text/html" width="100%" height="260" :src="courses[course].url" frameborder="0"></iframe>
		<v-container>
			<v-card :color="courses[course].color" :class="courses[course].text + '--text'">
				<v-container fluid grid-list-lg>
					<v-layout row>
						<v-flex xs7>
							<div>
								<div class="headline">{{courses[course].name}}</div>
								<div class="mt-2">{{courses[course].desc}}</div>
							</div>
						</v-flex>
						<v-flex xs5>
							<v-card-media
									:src="courses[course].img"
									height="90px"
									contain
						></v-card-media>
						</v-flex>
					</v-layout>
				</v-container>
				<v-progress-linear v-model="courses[course].progress" min="0" max="100" color="red" background-color="grey"></v-progress-linear>
			</v-card>
			<v-card class="mt-4">
				<v-container fluid>
					<h2>EasyRead</h2>
					<div v-for="(line, index) in courses[course].subtitles" :key="index">
						{{line}}
					</div>
				</v-container>
			</v-card>
		</v-container>
	</div>
</template>
		
<script>
	export default {
		data: () => {
			return {
				course: null,
				courses: {
					vacuum: {
						name: "Vacuum Essentials Level 6",
						desc: "It gets very interesting on Level 6 — learn more about vacuum cleaners and how to best use them.",
						color: "cyan darken-2",
						text: "white",
						img: "/001-vacuum-cleaner.svg",
						progress: 76,
						url: "https://www.youtube.com/embed/i3u27-oJzBY",
						subtitles: [
							"Hi. This is Travis on behalf of Expert Village",
							"talking to you about vacuuming, and what I",
							"want to talk to you about now is how do you",
							"vacuum a room? Where do you start? Do you",
							"back yourself into a corner? It's almost like",
							"painting, you know...painting a floor. What",
							"you want to do is when you come into a room,",
							"depending on whether it's your living room",
							"or your bedroom, what you are going to want",
							"to do is you are going to want to make sure",
							"that you probably end up at the entrance door",
							"into that particular room. What that's going",
							"to do is it is going to allow you to hide",
							"your footprints after your vacuuming. You",
							"know, a lot of people are tedious about...say",
							"you've got company coming over, and you want",
							"them to know that you vacuumed. Well, you",
							"are going to want to start on the outer edges",
							"of the room and pull yourself back to that",
							"doorway. That way, you leave no footprints.",
							"You leave no track marks and you can see that",
							"the room has been freshly vacuumed. And so,",
							"in this particular case, what I would do is",
							"I would start over towards the corner and",
							"back my way out. And I'll just show you what",
							"I mean by how...what we can actually do is",
							"put a couple of feet marks in the carpet.",
							"I'm not sure if that's going to show up real",
							"good on the film, but we'll do that and then",
							"I'll show you how we can disappear that and",
							"give it that freshly vacuumed look. So you",
							"can see how nice that looks when you actually",
							"pull the carpet back and there's no footprints,",
							"giving you a nice, fresh look."
						]
					},
					kitchen: {
						name: "Kitchen Chemistry",
						desc: "Master your skills in cleaning kitchens for restaurants and hotels in this 5-part course.",
						color: "yellow accent-4",
						text: "black",
						img: "/kitchen.png",
						progress: 43,
						url: "https://www.youtube.com/embed/Vos3br2docY",
						subtitles: [
							"A kitchen is like a newborn baby. It",
							"requires constant attention. The reason is",
							"we are always using our kitchen. It's the",
							"heart of the home. We're cooking in it.",
							"We're hanging out in it. I'm looking",
							"around my kitchen right now. There is like",
							"so much going on. There's old food.",
							"There's frying pans. There's dirt. There's",
							"dust. There's remnants from whatever I",
							"cooked. There's dishes that need to be",
							"tended to. This kitchen gets messy no",
							"matter how much we clean it.",
							"Many of you have asked me for my kitchen",
							"cleaning routine, something that I can",
							"show you that I do, which helps manage my",
							"kitchen on a day-to-day basis. I am glad",
							"to share it with you. And the frustrating",
							"thing about a kitchen routine is it feels",
							"like if you let your kitchen go, even for",
							"one day, it can feel so overwhelming and",
							"out of control. So I'm going to show you",
							"what I do to keep it simple, to keep it",
							"quick, and of course to keep my kitchen",
							"looking in tip-top shape with minimal",
							"effort.",
							"Okay. Let's get to it. Every morning,",
							"while making coffee or tea, empty your",
							"dishwasher. A dishwasher should be filled",
							"up with items from the night before, ran",
							"overnight, and emptied in the morning for",
							"a new start to the day. If you don't have",
							"a dishwasher, place all items in your",
							"drying rack away where they belong. It",
							"takes me about four minutes to unload a",
							"dishwasher. You can certainly spare that",
							"while you're waiting for your coffee.",
							"Wipe your counters and table down after",
							"breakfast, and finish off by placing any",
							"dishes in the dishwasher. Or hand-washing",
							"and placing them on a drying rack, and",
							"rinsing and shining your sink before you",
							"go. When everyone gets home from work or",
							"school, the rule needs to be that you",
							"empty all garbage and containers, and",
							"place anything that's dishwasher-able into",
							"the dishwasher. Or you hand-wash your",
							"containers right then and there. Don't",
							"leave anything out because it will pile",
							"up.",
							"I can't even begin to cook dinner unless",
							"my kitchen is clean, and that really does",
							"require clean counters and a dishwasher",
							"that is ready to be loaded. So that being",
							"said, once dinner has been prepared, place",
							"all your dishes into the dishwasher or",
							"hand-wash them, as well as pots and pans.",
							"Now, if something needs to be soaked, like",
							"a heavy-duty dirty casserole, soak it",
							"while you're eating so that it's got time,",
							"and when you're done eating you can clean",
							"it easily.",
							"Set your dishwasher to run overnight,",
							"because that'll help you save on energy",
							"and water costs. If you don't have enough",
							"dishes, just leave it until you do have",
							"enough to run a full cycle. Use a cloth",
							"and all-purpose disinfecting spray to",
							"clean your counters down. You can also do",
							"a spot check for fingerprints on doorknobs",
							"and cover fronts. This goes for appliances",
							"too, since they can easily get printed up.",
							"Make sure you include your stove top in",
							"the wipe-down as well.",
							"Empty your garbage, take out the",
							"recycling, and replace liners as required.",
							"This will help manage odors. Keeping your",
							"counters clutter-free is really important",
							"in maintaining your kitchen. So put",
							"everything back in its rightful place.",
							"Make sure that your countertop has",
							"everything neatly organized. A little",
							"trick I like to do is line everything up",
							"parallel and perpendicular to the edge of",
							"the counter. That way it looks",
							"super-clean.",
							"Spray your sink down with an all-purpose",
							"cleaner and sprinkle in an abrasive",
							"cleaner like baking soda. Scrub it with a",
							"soft sponge, rinse it, and shine it.",
							"Remove any debris at the bottom of the",
							"sink. To put the finishing touch on your",
							"kitchen, all you need to do is straighten",
							"up any tea towels, refill paper towels,",
							"and do a super-fast sweep of the floor if",
							"needed. Make sure your kitchen is ready to",
							"greet you bright and early tomorrow",
							"morning.",
							"What I reviewed was just a guideline. It's",
							"designed to sort of help you figure out",
							"what you need to do in your kitchen each",
							"day. But if you skip a day, or you don't",
							"do everything perfectly or exactly the way",
							"I showed you, that's okay. The important",
							"part is that you just do something and if",
							"you forget to do it one day, don't beat",
							"yourself up. Just pick up and start the",
							"next day.",
							"The question I get asked in every routine",
							"video is, 'How do I get my so and so to",
							"help me clean as well?' They're certainly",
							"welcome to watch this video if they're a",
							"willing participant. You can also have a",
							"conversation with them. We have a video",
							"about that and I'll link it for you at the",
							"end of this video. But keep in mind, not",
							"everybody thinks the way that you think",
							"and you are the one that values a clean",
							"space, or you think you could benefit from",
							"that clean space.",
							"So if no one is willing to help you, but",
							"you really want a clean kitchen, I would",
							"just encourage you to do it anyway. It's",
							"going to benefit you in the long run,",
							"because you're going to feel better about",
							"your kitchen, and you get the added",
							"benefit of feeling good about yourself",
							"because you contributed to making a",
							"beautiful space. That's got to be worth",
							"it. It might feel a little bit cumbersome",
							"at first to get into the groove of this",
							"routine, but I promise if you put it to",
							"the test, feel things out and adjust it",
							"based on what you need, it'll start to",
							"feel very natural and you will actually be",
							"so happy that you're doing it because the",
							"results are well worth it.",
							"This week's comment question is, 'What",
							"cleaning routine should we do next?' Let",
							"me know in the coments down below. If you",
							"felt motivated by this video to clean your",
							"kitchen, please take a picture and tag me",
							"on Instagram because I would love to see",
							"your hard work paying off. I'm",
							"@melissamaker. The cameraman for today and",
							"always is @thechadreynolds. He's also my",
							"husband, and we are @cleanmyspace. There's",
							"a button down there that lets me know you",
							"care. So click it if you liked this video",
							"and click this button right here to",
							"subscribe and begin your journey to a",
							"cleaner life. Thanks so much for watching,",
							"and we'll see you next time.",
							"It is that special time in the video where",
							"I get to throw your attention to two other",
							"videos I think you're going to love. The",
							"first one, and I referenced it earlier, is",
							"'How to Get Your Spouse to Clean, ' or",
							"partner, or whoever. I know it's an",
							"awkward conversation. I know it's a bone",
							"of contention, but we made a video about",
							"it and I think you're going to like it. We",
							"also have another video that you might",
							"want to check out, right over there. It's",
							"called something along the lines of 'How",
							"to Clean Your Sink.' It's a very",
							"informative video and it will show you how",
							"to get your sink crystal clean.",
							"Make sure to check out our blog,",
							"CleanMySpace.com, which is filled with all",
							"kinds of cleaning information, articles,",
							"product reviews, celebrity interviews and",
							"all kinds of other cool stuff. It's at",
							"CleanMySpace.com. We've got a link for it",
							"down below for you as well. Thanks again,",
							"and I'll see you next week."
						]
					},
					microfiber: {
						name: "Microfiber, Macropower",
						desc: "All you need to know about microfiber cloths and how to best use them in this short course.",
						color: "deep-purple",
						text: "white",
						img: "/flask.png",
						progress: 0,
						url: "https://www.youtube.com/embed/PUNqsX8hlU8",
						subtitles: [
							"How do you clean microfiber cloths?",
							"It's an excellent question and we're going",
							"to talk about that today.",
							"Hi there, I'm Angela Brown and this is Ask",
							"a House Cleaner.",
							"This is a show where you get to ask a house",
							"cleaning question",
							"and I get to help you find an answer.",
							"Now today's show is brought to us by MyCleaningConnection.com,",
							"which is a hub for all things house cleaning.",
							"And on there you will find some microfiber",
							"cloths in the different varieties we're going",
							"to be talking about today.",
							"All right, so the question today comes from",
							"a new guy that's starting a house cleaning",
							"business and he wants to know.",
							"Speaker 2: Hi Angela.",
							"I'm starting a house cleaning business.",
							"I used to work for a company and they used",
							"to wash their microfiber on the sanitize cycle,",
							"but I found, and have learned since, that",
							"heat deteriorates microfibers.",
							"So for myself I've been using bleach instead,",
							"which I know is also bad.",
							"But I've been using about a cup of bleach",
							"for an extra-large load on a top loading washer.",
							"So I was just wondering what you do if you",
							"use that, how you clean them, etc.",
							"Angela Brown: All right, that's an excellent",
							"question and yes, you're correct.",
							"The heat will destroy your microfiber cloths.",
							"So let's go back to a second for what is a",
							"microfiber cloth.",
							"Now, a cotton cloth is made of cotton and",
							"the fibers are kind of lumpy because that's",
							"what cotton is.",
							"They're globs of cotton.",
							"Now, a microfiber cloth is different in the",
							"sense that it's very scientific in its approach.",
							"And so the threads are about one one hundredth",
							"the width of a human hair.",
							"So when those are all blended together and",
							"all mixed together you have a very specific,",
							"uniform, consistent, drying fabric that you",
							"can use that's become very popular in the",
							"auto detailing industry and now also very",
							"popular in house cleaning.",
							"So back in the 1950s is when microfiber was",
							"really created and introduced.",
							"And the Japanese made it very popular in the 1970s",
							"and brought it to the auto detailing industry.",
							"And then in the 1990s microfiber became really",
							"popular and mainstream for regular homes and",
							"house cleaning and all that kind of stuff.",
							"But the regular way that you clean it is not",
							"the same way you would clean cotton cloths.",
							"So the first thing that I might mention is",
							"that if you are using microfiber cloths for",
							"house cleaning you need to know what the different",
							"fabrics are and what surfaces you want to",
							"use them on.",
							"Okay, so a plush microfiber is going to be",
							"used for detail work.",
							"A waffle weave microfiber cloth is going to",
							"be used for drying surfaces, and a flat one",
							"is going to be used for glass and flat surfaces.",
							"And then also, the suede microfiber is going",
							"to be used for coating work.",
							"And so that is going to be very popular, again,",
							"for the auto detailing and for the house cleaning",
							"you're going to be using it for dusting it",
							"and for drying and for polishing.",
							"So you need to know what the different microfiber",
							"cloths are what they are used for.",
							"Now, when you go to clean them you want to",
							"clean your microfiber cloths separately from",
							"everything else.",
							"You do not want to mix it with your cotton",
							"rags because you will get lint.",
							"And you don't want to mix it with any other",
							"clothes because what you're doing is you're",
							"pulling out all the dirt and all the dust",
							"from those microfibers that you're going to",
							"be using those cloths again, and you don't",
							"want all that stuff coming out and going into",
							"your clothes, and you don't want to mix and",
							"match fabrics.",
							"So you even want to separate your different",
							"microfiber cloths when you wash.",
							"So if you have a bucket back at your place",
							"of business, whether it's your home or if",
							"you have an office, you want to put your microfiber",
							"cloths in there to soak in a presoak detergent.",
							"Now, your presoak detergent is not going to",
							"be bleach.",
							"Please don't use bleach on your microfiber",
							"cloths.",
							"And you do not want to use anything that's strong,",
							"like fabric softener or anything like that.",
							"You want to use a liquid soap detergent for",
							"laundry",
							"that doesn't have any perfumes and no dyes.",
							"So you're talking something very eco-friendly,",
							"very simple,",
							"very soft as far as the chemicals that are involved. Okay?",
							"You don't want to use a lot of chemicals,",
							"just the soap.",
							"And I'll put links to that in the show notes",
							"so that you know what I'm talking about.",
							"Okay, so with that you want to soak your ragas",
							"and that will help loosen everything up.",
							"Then when you wash them you want to wash them",
							"on a gentle cycle that is warm, that has a",
							"warm attachment to it.",
							"You don't want to do hot, and you don't want",
							"to do cold.",
							"Cold won't get the dirt out or the grime out",
							"of your microfiber cloths.",
							"And the hot will destroy them, it will destroy",
							"those fine fibers.",
							"Then when you dry them, my preference is just",
							"to hang them up to dry, but you can throw",
							"them inside the dryer on a low tumble, low heat.",
							"Again, you do not want hot at all.",
							"No, in the back of my car I have this plastic",
							"shoe box that I keep microfiber cloths in.",
							"There are a couple of different kinds of microfiber",
							"cloths.",
							"Now, this first one does not have any seams",
							"around the edges.",
							"It's called a seamless microfiber cloth.",
							"And this is great for using, for example,",
							"on the outside of your car so that you don't",
							"run streaks that are caused by this edge.",
							"Now this is just a seamed edge on a different",
							"microfiber cloth and this one I actually use",
							"on the wheels.",
							"So I'm going to have two separate rags, and",
							"you will do this in cleaning as well, you'll",
							"have two separate cloths for different things.",
							"So this one has the little rim around it.",
							"This is the one that I use for the tires and",
							"the wheels.",
							"And it's going to be a little bit more grimy",
							"than this one for example.",
							"This is the one that I use on the skin and",
							"the outside shell of the car so that it doesn't",
							"grab the edge of that and then leave a little",
							"streak.",
							"So there are different cloths that you use",
							"for different things.",
							"And the important thing is that you realize",
							"that when you wash them you want to keep them",
							"separate.",
							"Now, this one is going to get more grimy than",
							"the other one because, like I say, I use it",
							"for the tires and the wheels of the car.",
							"So if you have a microfiber cloth and it gets",
							"really grimy you can still reuse it for a",
							"few times for that thing, like for my tires.",
							"I don't clean this rag ... I wash it after",
							"every use, but I don't boil it or whatever",
							"except maybe every three or four times.",
							"So when it gets really grimy and you do boil",
							"it what you do is you take a pan of water,",
							"you use one teaspoon of vinegar, white distilled",
							"vinegar per gallon of water, and then you",
							"drop your cloths in there and you let them",
							"boil for about 90 seconds.",
							"And you just stir them with a bit wooden spoon.",
							"And that way it kind of agitates them and",
							"it kind of mixes them up, but it loosens all",
							"the junk that are stuck inside your microfiber cloths.",
							"Then you grab some tongs and you take it out",
							"of the water, put it in the kitchen sink,",
							"when it cools down you do a regular load of wash",
							"for the very heavily stained microfiber cloths.",
							"So, I say don't use heat except when you're boiling it",
							"and that's why we don't do it very often.",
							"And with that it will remove the junk, but",
							"then like I said, 90 seconds.",
							"We don't want to do this on a half hour cycle",
							"or anything like that that you would do if",
							"you were to turn it on high heat in your dryer.",
							"So you want to be very specific and very careful",
							"about the heat because you don't want to destroy",
							"the fibers.",
							"So again, what we know about microfiber, there",
							"are different types, there are different plushes,",
							"they're used for different things, they need",
							"to be kept separately, and when you wash them",
							"they need to be kept separately.",
							"So don't wash your microfiber with anything",
							"else, only microfiber and they will last you",
							"a very, very long time.",
							"Now, there are reputable dealers that sell",
							"these and you can find cheap ones as well.",
							"The cheap ones will usually produce cheap",
							"results and the ones from reputable dealers",
							"will usually last you very long time.",
							"But they're not very expensive.",
							"You can actually find some really great microfiber",
							"cloths very inexpensively.",
							"And I'll put links in the show notes to those",
							"as well.",
							"So if you haven't used microfiber, if you're",
							"scared of microfiber,",
							"you don't know how to use it, jump in.",
							"It's a new fabric, it's fantastic, it's used",
							"for lots of different things",
							"in the cleaning business.",
							"And as far as cleaning them goes it's very,",
							"very easy.",
							"Just run them in a regular wash cycle on warm,",
							"not cold, not hot and use a very soft detergent",
							"with no dyes and no perfumes.",
							"All righty, that's my two cents for today.",
							"And until we meet again leave the world a",
							"cleaner place than when you found it.",
						]
					}
				}
			}
		},
		created() {
			this.course = this.$route.params.course;
		}
	}
</script>